<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.0.1</Version>
    <Authors>Zero-Bloat Sound</Authors>
    <Product>Zero-Bloat Sound</Product>
  </PropertyGroup>
</Project>
